[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "xibabel"
author = "Matthew Brett"
author-email = "matthew.brett@gmail.com"
home-page = "https://github.com/matthew-brett/xibabel"
classifiers = ['License :: OSI Approved :: BSD License']
