name: coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  XIB_DATA_PATH: ~/.xibabel/data

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Datalad on Unices
        uses: datalad/datalad-action/install@main
      - name: Install
        run: |
          pip install pytest-cov
          pip install -e '.[test,developer,optional]'
      - name: Cache Dataset
        uses: actions/cache@v4
        with:
          path: ${{ env.XIB_DATA_PATH }}
          key: ${{ runner.os }}-ds105
      - name: Get data
        run: python -m xibabel.testing minimal
      - name: Show environment
        run: env
      - name: Library tests
        run: |
          pytest --doctest-plus \
            --cov=xibabel  --cov-report xml  --cov-config=.coveragerc \
            src/xibabel
      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
