name: doc-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Apt update
        run: sudo apt update
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Datalad on Unices
        uses: datalad/datalad-action/install@main
      - name: Install
        run: |
          pip install -e '.[docs,developer]'
      - name: Show environment
        run: env
      - name: Build documentation
        run: |
          cd doc
          make html
      - name: Run documentation doctests
        run: |
          cd doc
          make clean
          make doctest
      - name: Check experiment notebooks
        run: |
          python -m ipykernel install --user --name xibabel
          jupytext --execute experiments/*.Rmd
