name: Test

on:
  push:
    branches:
      - debug-test
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  XIB_DATA_PATH: ~/.xibabel/data

jobs:
  test:
    strategy:
      matrix:
        python_version: ["3.12"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
      - uses: actions/checkout@v4
      - name: Test compile initial
        run: |
          python example.py
