name: Test

on:
  push:
    branches:
      - windows-test

permissions:
  contents: read # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  XIB_DATA_PATH: ~/.xibabel/data

jobs:
  test:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
      - name: Install
        run: |
          pip install -e .
      - name: Tests
        run: |
          pytest -v -v --doctest-plus src/xibabel
